version: '3.8'
services:
  app:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - POSTGRES_URL=jdbc:postgresql://database/balanceservice
      - SERVER_PORT=8080
    volumes:
      - ./:/app
    depends_on:
      - database

  database:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: balanceservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgres
      - postgres_config:/etc/postgres/conf.d

volumes:
  postgres_data:
  postgres_config:
